# Generated by Django 3.0.5 on 2020-10-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('monthly_income', models.IntegerField()),
                ('account_balance', models.IntegerField()),
                ('monthly_savings', models.IntegerField(default=0)),
                ('monthly_expenditure', models.IntegerField(default=0)),
                ('housing_expenditure', models.IntegerField(default=0)),
                ('transportation_expenditure', models.IntegerField(default=0)),
                ('food_expenditure', models.IntegerField(default=0)),
                ('healthcare_expenditure', models.IntegerField(default=0)),
                ('recreation_expenditure', models.IntegerField(default=0)),
                ('utilities_expenditure', models.IntegerField(default=0)),
                ('miscellaneous_expenditure', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
