# Generated by Django 3.0.5 on 2020-10-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='monthly_savings',
            field=models.IntegerField(),
        ),
    ]
