# Generated by Django 3.0.5 on 2020-10-11 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FinBot', '0002_auto_20201010_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='username',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='monthly_savings',
            field=models.IntegerField(default=0),
        ),
    ]
